name: Tests_CICD

on:
  push:
    branches:
      - feature/jenkins  # Trigger this action on the 'feature/jenkins' branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.12.5
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright Browsers (optional if needed for testing)
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # Install Allure Commandline on Windows
      - name: Install Allure Commandline
        run: |
            # Download Allure command-line tool for version 2.32.2
            Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.32.2/allure-2.32.2.zip" -OutFile "allure.zip"

            # Extract the zip file to the current directory
            Expand-Archive -Path "allure.zip" -DestinationPath "allure"

            # Verify the extraction, ensure allure.bat exists
            if (Test-Path "allure\allure-2.32.2\bin\allure.bat") {
            Write-Host "allure.bat found"
            } else {
            Write-Host "allure.bat not found"
            exit 1
            }

            # Move the Allure directory to a common location
            $allurePath = "C:\allure"
            if (-not (Test-Path $allurePath)) {
            New-Item -Path $allurePath -ItemType Directory
            }
            move-item -Path "allure\allure-2.32.2" -Destination $allurePath -Force

            # Persist Allure to PATH
            [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$allurePath\allure-2.32.2\bin", [System.EnvironmentVariableTarget]::Machine)

      # Verify Allure installation
      - name: Verify Allure installation
        run: |
                # Verify Allure is installed correctly
                & "C:\allure\allure-2.32.2\bin\allure.bat" --version

      # Run Tests with Allure results
      - name: Run Tests with Allure results
        continue-on-error: true
        run: |
                pytest --alluredir=allure-results --maxfail=1 --disable-warnings

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
                & "C:\allure\allure-2.32.2\bin\allure.bat" generate allure-results --clean -o allure-report

      # Upload Allure report as artifact
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
